/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "asn/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_MeasResultEUTRA_H_
#define	_MeasResultEUTRA_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysCellId.h"
#include "CellGlobalIdEUTRA.h"
#include "TrackingAreaCode.h"
#include <constr_SEQUENCE.h>
#include "RSRP-Range.h"
#include "RSRQ-Range.h"
#include <NativeEnumerated.h>
#include "RSRQ-Range-v1250.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasResultEUTRA__measResult__primaryPLMN_Suitable_r12 {
	MeasResultEUTRA__measResult__primaryPLMN_Suitable_r12_true	= 0
} e_MeasResultEUTRA__measResult__primaryPLMN_Suitable_r12;

/* Forward declarations */
struct PLMN_IdentityList2;
struct AdditionalSI_Info_r9;

/* MeasResultEUTRA */
typedef struct MeasResultEUTRA {
	PhysCellId_t	 physCellId;
	struct MeasResultEUTRA__cgi_Info {
		CellGlobalIdEUTRA_t	 cellGlobalId;
		TrackingAreaCode_t	 trackingAreaCode;
		struct PLMN_IdentityList2	*plmn_IdentityList	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *cgi_Info;
	struct MeasResultEUTRA__measResult {
		RSRP_Range_t	*rsrpResult	/* OPTIONAL */;
		RSRQ_Range_t	*rsrqResult	/* OPTIONAL */;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		struct AdditionalSI_Info_r9	*additionalSI_Info_r9	/* OPTIONAL */;
		long	*primaryPLMN_Suitable_r12	/* OPTIONAL */;
		RSRQ_Range_v1250_t	*measResult_v1250	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} measResult;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResultEUTRA_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_primaryPLMN_Suitable_r12_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MeasResultEUTRA;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasResultEUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasResultEUTRA_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasResultEUTRA_H_ */
#include <asn_internal.h>
