/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "asn/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_PDCP_Config_H_
#define	_PDCP_Config_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDCP_Config__discardTimer {
	PDCP_Config__discardTimer_ms50	= 0,
	PDCP_Config__discardTimer_ms100	= 1,
	PDCP_Config__discardTimer_ms150	= 2,
	PDCP_Config__discardTimer_ms300	= 3,
	PDCP_Config__discardTimer_ms500	= 4,
	PDCP_Config__discardTimer_ms750	= 5,
	PDCP_Config__discardTimer_ms1500	= 6,
	PDCP_Config__discardTimer_infinity	= 7
} e_PDCP_Config__discardTimer;
typedef enum PDCP_Config__rlc_UM__pdcp_SN_Size {
	PDCP_Config__rlc_UM__pdcp_SN_Size_len7bits	= 0,
	PDCP_Config__rlc_UM__pdcp_SN_Size_len12bits	= 1
} e_PDCP_Config__rlc_UM__pdcp_SN_Size;
typedef enum PDCP_Config__headerCompression_PR {
	PDCP_Config__headerCompression_PR_NOTHING,	/* No components present */
	PDCP_Config__headerCompression_PR_notUsed,
	PDCP_Config__headerCompression_PR_rohc
} PDCP_Config__headerCompression_PR;
typedef enum PDCP_Config__rn_IntegrityProtection_r10 {
	PDCP_Config__rn_IntegrityProtection_r10_enabled	= 0
} e_PDCP_Config__rn_IntegrityProtection_r10;
typedef enum PDCP_Config__pdcp_SN_Size_v1130 {
	PDCP_Config__pdcp_SN_Size_v1130_len15bits	= 0
} e_PDCP_Config__pdcp_SN_Size_v1130;
typedef enum PDCP_Config__t_Reordering_r12 {
	PDCP_Config__t_Reordering_r12_ms0	= 0,
	PDCP_Config__t_Reordering_r12_ms20	= 1,
	PDCP_Config__t_Reordering_r12_ms40	= 2,
	PDCP_Config__t_Reordering_r12_ms60	= 3,
	PDCP_Config__t_Reordering_r12_ms80	= 4,
	PDCP_Config__t_Reordering_r12_ms100	= 5,
	PDCP_Config__t_Reordering_r12_ms120	= 6,
	PDCP_Config__t_Reordering_r12_ms140	= 7,
	PDCP_Config__t_Reordering_r12_ms160	= 8,
	PDCP_Config__t_Reordering_r12_ms180	= 9,
	PDCP_Config__t_Reordering_r12_ms200	= 10,
	PDCP_Config__t_Reordering_r12_ms220	= 11,
	PDCP_Config__t_Reordering_r12_ms240	= 12,
	PDCP_Config__t_Reordering_r12_ms260	= 13,
	PDCP_Config__t_Reordering_r12_ms280	= 14,
	PDCP_Config__t_Reordering_r12_ms300	= 15,
	PDCP_Config__t_Reordering_r12_ms500	= 16,
	PDCP_Config__t_Reordering_r12_ms750	= 17,
	PDCP_Config__t_Reordering_r12_spare14	= 18,
	PDCP_Config__t_Reordering_r12_spare13	= 19,
	PDCP_Config__t_Reordering_r12_spare12	= 20,
	PDCP_Config__t_Reordering_r12_spare11	= 21,
	PDCP_Config__t_Reordering_r12_spare10	= 22,
	PDCP_Config__t_Reordering_r12_spare9	= 23,
	PDCP_Config__t_Reordering_r12_spare8	= 24,
	PDCP_Config__t_Reordering_r12_spare7	= 25,
	PDCP_Config__t_Reordering_r12_spare6	= 26,
	PDCP_Config__t_Reordering_r12_spare5	= 27,
	PDCP_Config__t_Reordering_r12_spare4	= 28,
	PDCP_Config__t_Reordering_r12_spare3	= 29,
	PDCP_Config__t_Reordering_r12_spare2	= 30,
	PDCP_Config__t_Reordering_r12_spare1	= 31
} e_PDCP_Config__t_Reordering_r12;

/* PDCP-Config */
typedef struct PDCP_Config {
	long	*discardTimer	/* OPTIONAL */;
	struct PDCP_Config__rlc_AM {
		BOOLEAN_t	 statusReportRequired;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *rlc_AM;
	struct PDCP_Config__rlc_UM {
		long	 pdcp_SN_Size;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *rlc_UM;
	struct PDCP_Config__headerCompression {
		PDCP_Config__headerCompression_PR present;
		union PDCP_Config__headerCompression_u {
			NULL_t	 notUsed;
			struct PDCP_Config__headerCompression__rohc {
				long	*maxCID	/* DEFAULT 15 */;
				struct PDCP_Config__headerCompression__rohc__profiles {
					BOOLEAN_t	 profile0x0001;
					BOOLEAN_t	 profile0x0002;
					BOOLEAN_t	 profile0x0003;
					BOOLEAN_t	 profile0x0004;
					BOOLEAN_t	 profile0x0006;
					BOOLEAN_t	 profile0x0101;
					BOOLEAN_t	 profile0x0102;
					BOOLEAN_t	 profile0x0103;
					BOOLEAN_t	 profile0x0104;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} profiles;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} rohc;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} headerCompression;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	long	*rn_IntegrityProtection_r10	/* OPTIONAL */;
	long	*pdcp_SN_Size_v1130	/* OPTIONAL */;
	BOOLEAN_t	*ul_DataSplitDRB_ViaSCG_r12	/* OPTIONAL */;
	long	*t_Reordering_r12	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDCP_Config_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_discardTimer_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_pdcp_SN_Size_14;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_rn_IntegrityProtection_r10_33;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_pdcp_SN_Size_v1130_35;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_t_Reordering_r12_38;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PDCP_Config;
extern asn_SEQUENCE_specifics_t asn_SPC_PDCP_Config_specs_1;
extern asn_TYPE_member_t asn_MBR_PDCP_Config_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _PDCP_Config_H_ */
#include <asn_internal.h>
