/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "asn/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "RadioResourceConfigDedicatedPSCell-r12.h"

#include "PhysicalConfigDedicated.h"
#include "SPS-Config.h"
#include "NAICS-AssistanceInfo-r12.h"
asn_TYPE_member_t asn_MBR_RadioResourceConfigDedicatedPSCell_r12_1[] = {
	{ ATF_POINTER, 3, offsetof(struct RadioResourceConfigDedicatedPSCell_r12, physicalConfigDedicatedPSCell_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysicalConfigDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"physicalConfigDedicatedPSCell-r12"
		},
	{ ATF_POINTER, 2, offsetof(struct RadioResourceConfigDedicatedPSCell_r12, sps_Config_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPS_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sps-Config-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct RadioResourceConfigDedicatedPSCell_r12, naics_Info_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NAICS_AssistanceInfo_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"naics-Info-r12"
		},
};
static const int asn_MAP_RadioResourceConfigDedicatedPSCell_r12_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RadioResourceConfigDedicatedPSCell_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physicalConfigDedicatedPSCell-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sps-Config-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* naics-Info-r12 */
};
asn_SEQUENCE_specifics_t asn_SPC_RadioResourceConfigDedicatedPSCell_r12_specs_1 = {
	sizeof(struct RadioResourceConfigDedicatedPSCell_r12),
	offsetof(struct RadioResourceConfigDedicatedPSCell_r12, _asn_ctx),
	asn_MAP_RadioResourceConfigDedicatedPSCell_r12_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RadioResourceConfigDedicatedPSCell_r12_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RadioResourceConfigDedicatedPSCell_r12 = {
	"RadioResourceConfigDedicatedPSCell-r12",
	"RadioResourceConfigDedicatedPSCell-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1,
	sizeof(asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1[0]), /* 1 */
	asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RadioResourceConfigDedicatedPSCell_r12_1,
	3,	/* Elements count */
	&asn_SPC_RadioResourceConfigDedicatedPSCell_r12_specs_1	/* Additional specs */
};

