/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "asn/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "SCG-ConfigPartSCG-r12.h"

#include "RadioResourceConfigDedicatedSCG-r12.h"
#include "SCellToReleaseList-r10.h"
#include "PSCellToAddMod-r12.h"
#include "SCellToAddModList-r10.h"
#include "MobilityControlInfoSCG-r12.h"
asn_TYPE_member_t asn_MBR_SCG_ConfigPartSCG_r12_1[] = {
	{ ATF_POINTER, 5, offsetof(struct SCG_ConfigPartSCG_r12, radioResourceConfigDedicatedSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioResourceConfigDedicatedSCG_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioResourceConfigDedicatedSCG-r12"
		},
	{ ATF_POINTER, 4, offsetof(struct SCG_ConfigPartSCG_r12, sCellToReleaseListSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellToReleaseList_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellToReleaseListSCG-r12"
		},
	{ ATF_POINTER, 3, offsetof(struct SCG_ConfigPartSCG_r12, pSCellToAddMod_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PSCellToAddMod_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pSCellToAddMod-r12"
		},
	{ ATF_POINTER, 2, offsetof(struct SCG_ConfigPartSCG_r12, sCellToAddModListSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellToAddModList_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellToAddModListSCG-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct SCG_ConfigPartSCG_r12, mobilityControlInfoSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MobilityControlInfoSCG_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mobilityControlInfoSCG-r12"
		},
};
static const int asn_MAP_SCG_ConfigPartSCG_r12_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_SCG_ConfigPartSCG_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SCG_ConfigPartSCG_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radioResourceConfigDedicatedSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sCellToReleaseListSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* pSCellToAddMod-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sCellToAddModListSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* mobilityControlInfoSCG-r12 */
};
asn_SEQUENCE_specifics_t asn_SPC_SCG_ConfigPartSCG_r12_specs_1 = {
	sizeof(struct SCG_ConfigPartSCG_r12),
	offsetof(struct SCG_ConfigPartSCG_r12, _asn_ctx),
	asn_MAP_SCG_ConfigPartSCG_r12_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SCG_ConfigPartSCG_r12_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SCG_ConfigPartSCG_r12 = {
	"SCG-ConfigPartSCG-r12",
	"SCG-ConfigPartSCG-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_SCG_ConfigPartSCG_r12_tags_1,
	sizeof(asn_DEF_SCG_ConfigPartSCG_r12_tags_1)
		/sizeof(asn_DEF_SCG_ConfigPartSCG_r12_tags_1[0]), /* 1 */
	asn_DEF_SCG_ConfigPartSCG_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_SCG_ConfigPartSCG_r12_tags_1)
		/sizeof(asn_DEF_SCG_ConfigPartSCG_r12_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SCG_ConfigPartSCG_r12_1,
	5,	/* Elements count */
	&asn_SPC_SCG_ConfigPartSCG_r12_specs_1	/* Additional specs */
};

