/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "asn/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "SL-DiscResourcePool-r12.h"

#include "TDD-Config.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_syncConfigIndex_r12_constraint_26(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_numRetx_r12_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_numRepetition_r12_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 50)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_discPeriod_r12_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_poolSelection_r12_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_txProbability_r12_constr_21 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_syncConfigIndex_r12_constr_28 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_numRetx_r12_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_numRepetition_r12_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  1,  50 }	/* (1..50) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_discPeriod_r12_value2enum_3[] = {
	{ 0,	4,	"rf32" },
	{ 1,	4,	"rf64" },
	{ 2,	5,	"rf128" },
	{ 3,	5,	"rf256" },
	{ 4,	5,	"rf512" },
	{ 5,	6,	"rf1024" },
	{ 6,	6,	"spare2" },
	{ 7,	5,	"spare" }
};
static const unsigned int asn_MAP_discPeriod_r12_enum2value_3[] = {
	5,	/* rf1024(5) */
	2,	/* rf128(2) */
	3,	/* rf256(3) */
	0,	/* rf32(0) */
	4,	/* rf512(4) */
	1,	/* rf64(1) */
	7,	/* spare(7) */
	6	/* spare2(6) */
};
static const asn_INTEGER_specifics_t asn_SPC_discPeriod_r12_specs_3 = {
	asn_MAP_discPeriod_r12_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_discPeriod_r12_enum2value_3,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_discPeriod_r12_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_discPeriod_r12_3 = {
	"discPeriod-r12",
	"discPeriod-r12",
	&asn_OP_NativeEnumerated,
	asn_DEF_discPeriod_r12_tags_3,
	sizeof(asn_DEF_discPeriod_r12_tags_3)
		/sizeof(asn_DEF_discPeriod_r12_tags_3[0]) - 1, /* 1 */
	asn_DEF_discPeriod_r12_tags_3,	/* Same as above */
	sizeof(asn_DEF_discPeriod_r12_tags_3)
		/sizeof(asn_DEF_discPeriod_r12_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_discPeriod_r12_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_discPeriod_r12_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_poolSelection_r12_18[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12__poolSelection_r12, choice.rsrpBased_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_PoolSelectionConfig_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsrpBased-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12__poolSelection_r12, choice.random_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"random-r12"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_poolSelection_r12_tag2el_18[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rsrpBased-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* random-r12 */
};
static asn_CHOICE_specifics_t asn_SPC_poolSelection_r12_specs_18 = {
	sizeof(struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12__poolSelection_r12),
	offsetof(struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12__poolSelection_r12, _asn_ctx),
	offsetof(struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12__poolSelection_r12, present),
	sizeof(((struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12__poolSelection_r12 *)0)->present),
	asn_MAP_poolSelection_r12_tag2el_18,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_poolSelection_r12_18 = {
	"poolSelection-r12",
	"poolSelection-r12",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_poolSelection_r12_constr_18, CHOICE_constraint },
	asn_MBR_poolSelection_r12_18,
	2,	/* Elements count */
	&asn_SPC_poolSelection_r12_specs_18	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_txProbability_r12_value2enum_21[] = {
	{ 0,	3,	"p25" },
	{ 1,	3,	"p50" },
	{ 2,	3,	"p75" },
	{ 3,	4,	"p100" }
};
static const unsigned int asn_MAP_txProbability_r12_enum2value_21[] = {
	3,	/* p100(3) */
	0,	/* p25(0) */
	1,	/* p50(1) */
	2	/* p75(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_txProbability_r12_specs_21 = {
	asn_MAP_txProbability_r12_value2enum_21,	/* "tag" => N; sorted by tag */
	asn_MAP_txProbability_r12_enum2value_21,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_txProbability_r12_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_txProbability_r12_21 = {
	"txProbability-r12",
	"txProbability-r12",
	&asn_OP_NativeEnumerated,
	asn_DEF_txProbability_r12_tags_21,
	sizeof(asn_DEF_txProbability_r12_tags_21)
		/sizeof(asn_DEF_txProbability_r12_tags_21[0]) - 1, /* 1 */
	asn_DEF_txProbability_r12_tags_21,	/* Same as above */
	sizeof(asn_DEF_txProbability_r12_tags_21)
		/sizeof(asn_DEF_txProbability_r12_tags_21[0]), /* 2 */
	{ 0, &asn_PER_type_txProbability_r12_constr_21, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_txProbability_r12_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ue_SelectedResourceConfig_r12_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12, poolSelection_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_poolSelection_r12_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"poolSelection-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12, txProbability_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_txProbability_r12_21,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"txProbability-r12"
		},
};
static const ber_tlv_tag_t asn_DEF_ue_SelectedResourceConfig_r12_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ue_SelectedResourceConfig_r12_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* poolSelection-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* txProbability-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ue_SelectedResourceConfig_r12_specs_17 = {
	sizeof(struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12),
	offsetof(struct SL_DiscResourcePool_r12__txParameters_r12__ue_SelectedResourceConfig_r12, _asn_ctx),
	asn_MAP_ue_SelectedResourceConfig_r12_tag2el_17,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ue_SelectedResourceConfig_r12_17 = {
	"ue-SelectedResourceConfig-r12",
	"ue-SelectedResourceConfig-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_ue_SelectedResourceConfig_r12_tags_17,
	sizeof(asn_DEF_ue_SelectedResourceConfig_r12_tags_17)
		/sizeof(asn_DEF_ue_SelectedResourceConfig_r12_tags_17[0]) - 1, /* 1 */
	asn_DEF_ue_SelectedResourceConfig_r12_tags_17,	/* Same as above */
	sizeof(asn_DEF_ue_SelectedResourceConfig_r12_tags_17)
		/sizeof(asn_DEF_ue_SelectedResourceConfig_r12_tags_17[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ue_SelectedResourceConfig_r12_17,
	2,	/* Elements count */
	&asn_SPC_ue_SelectedResourceConfig_r12_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_txParameters_r12_15[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12__txParameters_r12, txParametersGeneral_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_TxParameters_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"txParametersGeneral-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct SL_DiscResourcePool_r12__txParameters_r12, ue_SelectedResourceConfig_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ue_SelectedResourceConfig_r12_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-SelectedResourceConfig-r12"
		},
};
static const int asn_MAP_txParameters_r12_oms_15[] = { 1 };
static const ber_tlv_tag_t asn_DEF_txParameters_r12_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_txParameters_r12_tag2el_15[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* txParametersGeneral-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ue-SelectedResourceConfig-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_txParameters_r12_specs_15 = {
	sizeof(struct SL_DiscResourcePool_r12__txParameters_r12),
	offsetof(struct SL_DiscResourcePool_r12__txParameters_r12, _asn_ctx),
	asn_MAP_txParameters_r12_tag2el_15,
	2,	/* Count of tags in the map */
	asn_MAP_txParameters_r12_oms_15,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_txParameters_r12_15 = {
	"txParameters-r12",
	"txParameters-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_txParameters_r12_tags_15,
	sizeof(asn_DEF_txParameters_r12_tags_15)
		/sizeof(asn_DEF_txParameters_r12_tags_15[0]) - 1, /* 1 */
	asn_DEF_txParameters_r12_tags_15,	/* Same as above */
	sizeof(asn_DEF_txParameters_r12_tags_15)
		/sizeof(asn_DEF_txParameters_r12_tags_15[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_txParameters_r12_15,
	2,	/* Elements count */
	&asn_SPC_txParameters_r12_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_rxParameters_r12_26[] = {
	{ ATF_POINTER, 1, offsetof(struct SL_DiscResourcePool_r12__rxParameters_r12, tdd_Config_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TDD_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tdd-Config-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12__rxParameters_r12, syncConfigIndex_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_syncConfigIndex_r12_constr_28,  memb_syncConfigIndex_r12_constraint_26 },
		0, 0, /* No default value */
		"syncConfigIndex-r12"
		},
};
static const int asn_MAP_rxParameters_r12_oms_26[] = { 0 };
static const ber_tlv_tag_t asn_DEF_rxParameters_r12_tags_26[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_rxParameters_r12_tag2el_26[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tdd-Config-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* syncConfigIndex-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_rxParameters_r12_specs_26 = {
	sizeof(struct SL_DiscResourcePool_r12__rxParameters_r12),
	offsetof(struct SL_DiscResourcePool_r12__rxParameters_r12, _asn_ctx),
	asn_MAP_rxParameters_r12_tag2el_26,
	2,	/* Count of tags in the map */
	asn_MAP_rxParameters_r12_oms_26,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rxParameters_r12_26 = {
	"rxParameters-r12",
	"rxParameters-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_rxParameters_r12_tags_26,
	sizeof(asn_DEF_rxParameters_r12_tags_26)
		/sizeof(asn_DEF_rxParameters_r12_tags_26[0]) - 1, /* 1 */
	asn_DEF_rxParameters_r12_tags_26,	/* Same as above */
	sizeof(asn_DEF_rxParameters_r12_tags_26)
		/sizeof(asn_DEF_rxParameters_r12_tags_26[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_rxParameters_r12_26,
	2,	/* Elements count */
	&asn_SPC_rxParameters_r12_specs_26	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SL_DiscResourcePool_r12_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12, cp_Len_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CP_Len_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cp-Len-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12, discPeriod_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_discPeriod_r12_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"discPeriod-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12, numRetx_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_numRetx_r12_constr_12,  memb_numRetx_r12_constraint_1 },
		0, 0, /* No default value */
		"numRetx-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12, numRepetition_r12),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_numRepetition_r12_constr_13,  memb_numRepetition_r12_constraint_1 },
		0, 0, /* No default value */
		"numRepetition-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_DiscResourcePool_r12, tf_ResourceConfig_r12),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_TF_ResourceConfig_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tf-ResourceConfig-r12"
		},
	{ ATF_POINTER, 2, offsetof(struct SL_DiscResourcePool_r12, txParameters_r12),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_txParameters_r12_15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"txParameters-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct SL_DiscResourcePool_r12, rxParameters_r12),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_rxParameters_r12_26,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rxParameters-r12"
		},
};
static const int asn_MAP_SL_DiscResourcePool_r12_oms_1[] = { 5, 6 };
static const ber_tlv_tag_t asn_DEF_SL_DiscResourcePool_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SL_DiscResourcePool_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cp-Len-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* discPeriod-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* numRetx-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* numRepetition-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* tf-ResourceConfig-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* txParameters-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* rxParameters-r12 */
};
asn_SEQUENCE_specifics_t asn_SPC_SL_DiscResourcePool_r12_specs_1 = {
	sizeof(struct SL_DiscResourcePool_r12),
	offsetof(struct SL_DiscResourcePool_r12, _asn_ctx),
	asn_MAP_SL_DiscResourcePool_r12_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_SL_DiscResourcePool_r12_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SL_DiscResourcePool_r12 = {
	"SL-DiscResourcePool-r12",
	"SL-DiscResourcePool-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_SL_DiscResourcePool_r12_tags_1,
	sizeof(asn_DEF_SL_DiscResourcePool_r12_tags_1)
		/sizeof(asn_DEF_SL_DiscResourcePool_r12_tags_1[0]), /* 1 */
	asn_DEF_SL_DiscResourcePool_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_SL_DiscResourcePool_r12_tags_1)
		/sizeof(asn_DEF_SL_DiscResourcePool_r12_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SL_DiscResourcePool_r12_1,
	7,	/* Elements count */
	&asn_SPC_SL_DiscResourcePool_r12_specs_1	/* Additional specs */
};

