/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "asn/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SystemInformationBlockType19_r12_H_
#define	_SystemInformationBlockType19_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "SL-DiscRxPoolList-r12.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SL_CarrierFreqInfoList_r12;
struct SL_DiscTxPoolList_r12;
struct SL_DiscTxPowerInfoList_r12;
struct SL_SyncConfigList_r12;

/* SystemInformationBlockType19-r12 */
typedef struct SystemInformationBlockType19_r12 {
	struct SystemInformationBlockType19_r12__discConfig_r12 {
		SL_DiscRxPoolList_r12_t	 discRxPool_r12;
		struct SL_DiscTxPoolList_r12	*discTxPoolCommon_r12	/* OPTIONAL */;
		struct SL_DiscTxPowerInfoList_r12	*discTxPowerInfo_r12	/* OPTIONAL */;
		struct SL_SyncConfigList_r12	*discSyncConfig_r12	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *discConfig_r12;
	struct SL_CarrierFreqInfoList_r12	*discInterFreqList_r12	/* OPTIONAL */;
	OCTET_STRING_t	*lateNonCriticalExtension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformationBlockType19_r12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType19_r12;
extern asn_SEQUENCE_specifics_t asn_SPC_SystemInformationBlockType19_r12_specs_1;
extern asn_TYPE_member_t asn_MBR_SystemInformationBlockType19_r12_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SystemInformationBlockType19_r12_H_ */
#include <asn_internal.h>
