/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "asn/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "SystemInformationBlockType19-r12.h"

#include "SL-CarrierFreqInfoList-r12.h"
#include "SL-DiscTxPoolList-r12.h"
#include "SL-DiscTxPowerInfoList-r12.h"
#include "SL-SyncConfigList-r12.h"
static asn_TYPE_member_t asn_MBR_discConfig_r12_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType19_r12__discConfig_r12, discRxPool_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_DiscRxPoolList_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"discRxPool-r12"
		},
	{ ATF_POINTER, 3, offsetof(struct SystemInformationBlockType19_r12__discConfig_r12, discTxPoolCommon_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_DiscTxPoolList_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"discTxPoolCommon-r12"
		},
	{ ATF_POINTER, 2, offsetof(struct SystemInformationBlockType19_r12__discConfig_r12, discTxPowerInfo_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_DiscTxPowerInfoList_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"discTxPowerInfo-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType19_r12__discConfig_r12, discSyncConfig_r12),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_SyncConfigList_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"discSyncConfig-r12"
		},
};
static const int asn_MAP_discConfig_r12_oms_2[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_discConfig_r12_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_discConfig_r12_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* discRxPool-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* discTxPoolCommon-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* discTxPowerInfo-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* discSyncConfig-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_discConfig_r12_specs_2 = {
	sizeof(struct SystemInformationBlockType19_r12__discConfig_r12),
	offsetof(struct SystemInformationBlockType19_r12__discConfig_r12, _asn_ctx),
	asn_MAP_discConfig_r12_tag2el_2,
	4,	/* Count of tags in the map */
	asn_MAP_discConfig_r12_oms_2,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_discConfig_r12_2 = {
	"discConfig-r12",
	"discConfig-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_discConfig_r12_tags_2,
	sizeof(asn_DEF_discConfig_r12_tags_2)
		/sizeof(asn_DEF_discConfig_r12_tags_2[0]) - 1, /* 1 */
	asn_DEF_discConfig_r12_tags_2,	/* Same as above */
	sizeof(asn_DEF_discConfig_r12_tags_2)
		/sizeof(asn_DEF_discConfig_r12_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_discConfig_r12_2,
	4,	/* Elements count */
	&asn_SPC_discConfig_r12_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SystemInformationBlockType19_r12_1[] = {
	{ ATF_POINTER, 3, offsetof(struct SystemInformationBlockType19_r12, discConfig_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_discConfig_r12_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"discConfig-r12"
		},
	{ ATF_POINTER, 2, offsetof(struct SystemInformationBlockType19_r12, discInterFreqList_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CarrierFreqInfoList_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"discInterFreqList-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType19_r12, lateNonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lateNonCriticalExtension"
		},
};
static const int asn_MAP_SystemInformationBlockType19_r12_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_SystemInformationBlockType19_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SystemInformationBlockType19_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* discConfig-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* discInterFreqList-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* lateNonCriticalExtension */
};
asn_SEQUENCE_specifics_t asn_SPC_SystemInformationBlockType19_r12_specs_1 = {
	sizeof(struct SystemInformationBlockType19_r12),
	offsetof(struct SystemInformationBlockType19_r12, _asn_ctx),
	asn_MAP_SystemInformationBlockType19_r12_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_SystemInformationBlockType19_r12_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType19_r12 = {
	"SystemInformationBlockType19-r12",
	"SystemInformationBlockType19-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_SystemInformationBlockType19_r12_tags_1,
	sizeof(asn_DEF_SystemInformationBlockType19_r12_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType19_r12_tags_1[0]), /* 1 */
	asn_DEF_SystemInformationBlockType19_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_SystemInformationBlockType19_r12_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType19_r12_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SystemInformationBlockType19_r12_1,
	3,	/* Elements count */
	&asn_SPC_SystemInformationBlockType19_r12_specs_1	/* Additional specs */
};

